/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/8c52cc37-6486-4f5e-8c0b-4cf428a67374

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led;
  CloudTemperatureSensor temp;
  CloudLight ledBlau;
  CloudRelativeHumidity humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"


#define DHTPIN 5

#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);

//const int LED = 2;
const int PIN_RED = 4;
const int PIN_YELLOW = 7;
const int PIN_GREEN = 8;
const int pinBlau = 2;
#define pinBlau 2

void setup() {
    // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  
  pinMode(PIN_RED, OUTPUT);
  pinMode(PIN_YELLOW, OUTPUT);
  pinMode(PIN_GREEN, OUTPUT);
  pinMode(pinBlau, OUTPUT);
  
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  
  dht.begin();

  // Defined in thingProperties.h
  initProperties();
    // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(3);
  ArduinoCloud.printDebugInfo();
}


void loop() {
  ArduinoCloud.update();
  // Your code here
  onLedChange();
  DHT_SENSOR_READ();
  onLedBlauChange();
    if(ledBlau==1)
  {
    digitalWrite(pinBlau, HIGH);
  }
  else
  {
    digitalWrite(pinBlau, LOW);
  }
   if (led == 1) {
    
    digitalWrite(PIN_RED, HIGH);
    delay(1500);

    digitalWrite(PIN_RED,LOW);
    digitalWrite(PIN_YELLOW, HIGH);
    delay(1500);
    digitalWrite(PIN_YELLOW, LOW);
    digitalWrite(PIN_GREEN,HIGH);
    delay(1500);
    digitalWrite(PIN_GREEN,LOW);
  }
  else
  {
    digitalWrite(PIN_RED, LOW);
    digitalWrite(PIN_YELLOW,LOW);
    digitalWrite(PIN_GREEN,LOW);
  }
 
} 

/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  
  
  // Set all output to LOW in order to turn all LEDs off
 // digitalWrite(PIN_RED,LOW);
 // digitalWrite(PIN_YELLOW,LOW);
 // digitalWrite(PIN_GREEN,LOW);
  
 
}


void DHT_SENSOR_READ(){
  
  float h = dht.readHumidity();
  float t  = dht.readTemperature();
  
  temp = t; 
  humidity=h;
  
  Serial.print("Temperature: "); Serial.println(t);
  Serial.print("Humidity: "); Serial.println(h);
  delay(1000);
}


/*
  Since LedBlau is READ_WRITE variable, onLedBlauChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedBlauChange()  {
  
}
